### ISSUE TITLE
Python Function For Checking API Limits

### ISSUE THREAD

**Issue by JEnduriumK** [agarcia169/4306-Donaldson-Project#27]

**Comment by Abalogun2** [comment]
ok figured how to pull the limits of the developer account

will be trying it out on a get tweet or tweet id to see if dictionary entries in header bracket change

**Comment by JEnduriumK** [comment]
Also consider having a function that provides something like a percentage of how many of our limit remain. 

For example: `'x-rate-limit-limit' / 'x-rate-limit-remaining'`. Or 296/300, in the one example we experimented with.

We'll also probably need a way of grabbing reset times (or maybe seconds until reset?).

**Comment by JEnduriumK** [comment]
Bola had some success with something along the lines of
```python
tweetex = tweepy.Client(bearer_token=BEARER_TOKEN, return_type=requests.Response)
# -rate-limit found by peering into headers[] file
print(tweetex.get_user(username='Honda').headers['x-rate-limit-remaining'])
print(tweetex.get_user(username='Honda').headers['x-rate-limit-limit'])
print(tweetex.get_user(username='Honda').headers['x-rate-limit-reset'])
percentage = float(tweetex.get_user(username='Honda').headers['x-rate-limit-remaining']) / float(tweetex.get_user(username='Honda').headers['x-rate-limit-limit'])
print (percentage)
```
but it turns out that Tweepy's design actually eliminates the API information if you stick with Tweepy's data structure. If you instead make a lower level call to the `requests.Response` data type that Tweepy is built off of, you can get the API information, but then all the Twitter data isn't nicely massaged and formatted for easy use. At which point, you're eliminating some of the reason why you're using Tweepy. 

I've made a [pull request](https://github.com/tweepy/tweepy/pull/1997) (that was accepted/merged) with Tweepy to maybe offer us an easy workaround, but we may need to consider alternatives, such as grabbing the data once with an API call (costing an API call or two) and just tracking how we're using it on our end, when it will reset, etc. Particularly since the most the dev was willing to do at this time was offer a workaround as a _function, which (as I understand it) are generally considered non-public and thus safe to break whenever, so we can't rely on it working.

**Comment by JEnduriumK** [comment]
I'm thinking we might need to build some sort of self-tracked limiter into the tdConnector thing, where our shared Tweepy connection exists. Something that will have hard coded values on what we know the limits are, occasionally burning an API request to grab limit amounts, and something to track reset times so that it resets what we _think_ our API usage is at when the time comes. 

We need the ability to ask our tdConnector "hey, is it safe to make this request?" and for it to have a good guess for a response. 

Twitter *will* boot us if we slam their API too hard past their limits.

**Comment by JEnduriumK** [comment]
I had to slam the API over and over again (getting a trickle of Tweets in each time, I think one or two companies haven't fully downloaded the full five years) and I finally hit an API limit. Here's an example bit of output, in case we care:

```
Traceback (most recent call last):
  File "g:\College\Software Engineering\repository\4306-Donaldson-Project\src\donaldson_asu_twitter\__main__.py", line 219, in <module>
    main()
  File "g:\College\Software Engineering\repository\4306-Donaldson-Project\src\donaldson_asu_twitter\__main__.py", line 199, in main
    AddTweetsToDB.refresh_tweets(id)
  File "G:\College\Software Engineering\repository\4306-Donaldson-Project\src\donaldson_asu_twitter\TweetManagement\AddTweetsToDB.py", line 120, in refresh_tweets
    retrieve_older_tweets(theUserID, **copyOfKwargs)
  File "G:\College\Software Engineering\repository\4306-Donaldson-Project\src\donaldson_asu_twitter\TweetManagement\AddTweetsToDB.py", line 92, in retrieve_older_tweets
    _retrieve_tweets(theUserID, **kwargs)
  File "G:\College\Software Engineering\repository\4306-Donaldson-Project\src\donaldson_asu_twitter\TweetManagement\AddTweetsToDB.py", line 132, in _retrieve_tweets
    for thisResponse in tweepy.Paginator(thisTwitterClient.get_users_tweets, theUserID, **argumentDictionary):
  File "C:\Program Files\Python310\tweepy\pagination.py", line 98, in __next__
    response = self.method(*self.args, **self.kwargs)
  File "C:\Program Files\Python310\tweepy\client.py", line 1565, in get_users_tweets
    return self._make_request(
  File "C:\Program Files\Python310\tweepy\client.py", line 126, in _make_request
    response = self.request(method, route, params=request_params,
  File "C:\Program Files\Python310\tweepy\client.py", line 114, in request
    raise TooManyRequests(response)
tweepy.errors.TooManyRequests: 429 Too Many Requests
Too Many Requests
```
